### ISSUE TITLE
update angular-dashboard-framework to 0.5.0

### ISSUE THREAD

**Issue by geshan** [sdorra/adf-dynamic-example#3]
I tried updating it in the bower.json but it did not work or I would have sent a PR.

**Comment by sdorra** [comment]
You are right there was an error with the minified version of v0.5.0. I've created v0.5.1 which fixes the problem.

**Comment by geshan** [comment]
thanks, so will just updating bower.json work now?

**Comment by sdorra** [comment]
I've already updated the adf-dynamic-example:

* [41231ad7](https://github.com/sdorra/adf-dynamic-example/commit/41231ad71e4c5a2a78acff4d9994fad85c0015f3)

**Comment by geshan** [comment]
Thanks, its working but I don't see the new widgets like the ones of github.

**Comment by sdorra** [comment]
The "sample" widgets are not part of the bower release (i will change this with v0.6.0). The adf-dynamic-example comes currently with its own set of [widgets](https://github.com/sdorra/adf-dynamic-example/tree/41231ad71e4c5a2a78acff4d9994fad85c0015f3/public/scripts/widgets).

**Comment by geshan** [comment]
will replacing them from the adf repo work? or will it need more changes?

**Comment by sdorra** [comment]
Yes, you have to load the scripts in the [index.html](https://github.com/sdorra/adf-dynamic-example/blob/master/public/index.html#L111) and define a dependency in the main [module](https://github.com/sdorra/adf-dynamic-example/blob/master/public/scripts/app.js#L27).

**Comment by geshan** [comment]
ok will check it out thanks, if you have time do have a look at this : https://github.com/sdorra/angular-dashboard-framework/issues/53
