### ISSUE TITLE
angular-dashboard-framework Sortable.create return undefined

### ISSUE THREAD

**Issue by moayadRajeh** [sdorra/adf-dynamic-example#5]
i'm trying to run The source of the angular-dashboard-framework demo (https://github.com/sdorra/angular-dashboard-framework/tree/master/sample)

Sortable.create function returns undefined.

**Comment by sdorra** [comment]
It look like you have forgotten to call  "bower install". However this has nothing to do with the adf-dynamic-example, next time please open the tickets for the angular-dashboard-framework at the angular-dashboard-framework repository.
