### ISSUE TITLE
How to use GULP to make a 'dist' folder or some kind of distribution package?

### ISSUE THREAD

**Issue by boltex** [sdorra/adf-dynamic-example#9]
Hello! 

I have made a more complex dashboard system from this 'adf-dynamic-example' example repo.

I am kind of a newbie with regards to gulp and 'compiled-minified-etc...' web projects. 

Do you have a gulp file, or any tips to make one, in order to 'compile' this project into a 'dist' folder?

Many thanks for your time !  
:)

**Comment by sdorra** [comment]
There a lot of examples out there. I recommend using [yeoman](http://yeoman.io/) for a productive setup.

**Comment by boltex** [comment]
Thanks! I figured it out!
